# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import interface_pb2 as interface__pb2


class CoordinationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tick = channel.unary_unary(
                '/coordination.Coordination/Tick',
                request_serializer=interface__pb2.TickRequest.SerializeToString,
                response_deserializer=interface__pb2.TickResponse.FromString,
                )


class CoordinationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Tick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tick': grpc.unary_unary_rpc_method_handler(
                    servicer.Tick,
                    request_deserializer=interface__pb2.TickRequest.FromString,
                    response_serializer=interface__pb2.TickResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coordination.Coordination', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Coordination(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Tick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coordination.Coordination/Tick',
            interface__pb2.TickRequest.SerializeToString,
            interface__pb2.TickResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
