# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterface.proto\x12\x0c\x63oordination\"\x1c\n\x04Vec2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\xff\x01\n\x0bTickRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\x08position\x18\x02 \x01(\x0b\x32\x12.coordination.Vec2\x12\x0e\n\x06radius\x18\x03 \x01(\x02\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x35\n\x06others\x18\x05 \x03(\x0b\x32%.coordination.TickRequest.Participant\x1a\x63\n\x0bParticipant\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\x08position\x18\x02 \x01(\x0b\x32\x12.coordination.Vec2\x12\x0e\n\x06radius\x18\x03 \x01(\x02\x12\x12\n\nconfidence\x18\x04 \x01(\x02\"N\n\x0cTickResponse\x12-\n\x0cnew_velocity\x18\x01 \x01(\x0b\x32\x12.coordination.Vec2H\x00\x88\x01\x01\x42\x0f\n\r_new_velocity2M\n\x0c\x43oordination\x12=\n\x04Tick\x12\x19.coordination.TickRequest\x1a\x1a.coordination.TickResponseb\x06proto3')



_VEC2 = DESCRIPTOR.message_types_by_name['Vec2']
_TICKREQUEST = DESCRIPTOR.message_types_by_name['TickRequest']
_TICKREQUEST_PARTICIPANT = _TICKREQUEST.nested_types_by_name['Participant']
_TICKRESPONSE = DESCRIPTOR.message_types_by_name['TickResponse']
Vec2 = _reflection.GeneratedProtocolMessageType('Vec2', (_message.Message,), {
  'DESCRIPTOR' : _VEC2,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:coordination.Vec2)
  })
_sym_db.RegisterMessage(Vec2)

TickRequest = _reflection.GeneratedProtocolMessageType('TickRequest', (_message.Message,), {

  'Participant' : _reflection.GeneratedProtocolMessageType('Participant', (_message.Message,), {
    'DESCRIPTOR' : _TICKREQUEST_PARTICIPANT,
    '__module__' : 'interface_pb2'
    # @@protoc_insertion_point(class_scope:coordination.TickRequest.Participant)
    })
  ,
  'DESCRIPTOR' : _TICKREQUEST,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:coordination.TickRequest)
  })
_sym_db.RegisterMessage(TickRequest)
_sym_db.RegisterMessage(TickRequest.Participant)

TickResponse = _reflection.GeneratedProtocolMessageType('TickResponse', (_message.Message,), {
  'DESCRIPTOR' : _TICKRESPONSE,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:coordination.TickResponse)
  })
_sym_db.RegisterMessage(TickResponse)

_COORDINATION = DESCRIPTOR.services_by_name['Coordination']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEC2._serialized_start=33
  _VEC2._serialized_end=61
  _TICKREQUEST._serialized_start=64
  _TICKREQUEST._serialized_end=319
  _TICKREQUEST_PARTICIPANT._serialized_start=220
  _TICKREQUEST_PARTICIPANT._serialized_end=319
  _TICKRESPONSE._serialized_start=321
  _TICKRESPONSE._serialized_end=399
  _COORDINATION._serialized_start=401
  _COORDINATION._serialized_end=478
# @@protoc_insertion_point(module_scope)
