version: "3.9"
services:
  ros:
    build: ./
    volumes:
      - ./:/ros
      - /tmp/shared:/shared
    # add environment variable
    environment:
      - WEBOTS_SHARED_FOLDER=/tmp/shared:/shared
